---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rockmkdl/public_html/
    - export VITE_API_URL=https://store-api.rockmission.co.za
    - npm ci
    - npm run build
    - /bin/cp -R dist/. $DEPLOYPATH